### ISSUE TITLE
window_heterozygosity.py example files?

### ISSUE THREAD

**Issue by DrPintoThe2nd** [drewschield/Comparative-Genomics-Tools#1]
Hi Drew,

Thanks for making these scripts available! The slidingwindow_gc_content.py has worked flawlessly for me!

I was wondering if you could provide example files for using the window_heterozygosity.py script.. Daren's script outputs a tab-delimited file (seemingly) analogous to a vcf file.. can you simply convert a called vcf file to a tab-delimited file (e.g. https://vcf-kit.readthedocs.io/en/latest/vcf2tsv/) and jump into this script? If this is the "<het.txt>" file, than what is in the "<windowfile.txt>" file and what is the format of that file?

Apologies in advance if I've missed something in either your's or Daren's documentation!!
Thanks again!
Best,
bjp

The principle

**Comment by drewschield** [comment]
Hey Brendan,

No problem! I’m glad they are useful to you.

My windowed heterozygosity script relies on a ‘window file’ that I generated using bedtools ‘make windows’ function, but you can generate one however makes sense for you. The window file just needs to follow the chromosome, start position, end position format (separated by tabs), as in a BED file. You are correct about Daren’s calcHet output - it’s a fairly standard tab-delimited output that has the heterozygosity for each SNP position in the last column.

I’ve attached a zipped folder with example files, including actual calcHet output and a 100kb genomic window BED file I used for my analyses. To save space, I just included data for the first 11 Mb of data for chromosome 1 of my species. I generated the ‘test.out.txt’ output file using the command:

python window_heterozygosity.py window_100kb.bed calcHet_out.het.txt test.out.txt

Let me know if this is what you were looking for, and if you have any additional questions. Word of warning - both the calcHet and window_heterozygosity.py scripts can take a long time on a whole genome, and will take longer if the genomic windows are at higher resolution. So, these can be good analyses to kick off during lunch or overnight.

Best,
Drew


On Aug 12, 2019, at 11:09 AM, Brendan J. Pinto <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Drew,

Thanks for making these scripts available! The slidingwindow_gc_content.py has worked flawlessly for me!

I was wondering if you could provide example files for using the window_heterozygosity.py script.. Daren's script outputs a tab-delimited file (seemingly) analogous to a vcf file.. can you simply convert a called vcf file to a tab-delimited file (e.g. https://vcf-kit.readthedocs.io/en/latest/vcf2tsv/<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvcf-kit.readthedocs.io%2Fen%2Flatest%2Fvcf2tsv%2F&data=02%7C01%7Cdschield%40uta.edu%7C13e3cdc0b3bd44b8d44108d71f3f6e55%7C5cdc5b43d7be4caa8173729e3b0a62d9%7C0%7C0%7C637012229600485235&sdata=CVaVijyMkLTsRrC5nYGknK91fTvsscC%2B%2BCJOV3tzfJs%3D&reserved=0>) and jump into this script? If this is the "<het.txt>" file, than what is in the "<windowfile.txt>" file and what is the format of that file?

Apologies in advance if I've missed something in either your's or Daren's documentation!!
Thanks again!
Best,
bjp

The principle
